import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../scss/globals.scss";
import Header from "@/widgets/Header";
import SidebarContainer from "@/widgets/SideBar";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const user = {
  firstName: "Имя",
  lastName: "Фамилия",
  email: "email@example.com",
  phone: "123-456-7890",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />

        {children}
      </body>
    </html>
  );
}
